# Generated by Django 5.2.1 on 2025-05-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taska_app', '0002_tasklist_taskitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_undelete', 'Can restore deleted users')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'),
        ),
    ]
