# Generated by Django 5.2.1 on 2025-05-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taska_app', '0003_alter_user_options_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskList',
            new_name='Projects',
        ),
        migrations.RenameField(
            model_name='taskitem',
            old_name='task_list',
            new_name='projects',
        ),
    ]
