# Generated by Django 5.2.1 on 2025-05-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taska_app', '0004_rename_tasklist_projects_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskItem',
            new_name='Tasks',
        ),
    ]
