# Generated by Django 5.2.1 on 2025-05-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taska_app', '0006_projects_due_date_projects_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='projects',
            new_name='project',
        ),
    ]
