# Generated by Django 5.2.1 on 2025-05-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taska_app', '0007_rename_projects_project_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
